// Generates assets/atomic-age/tokens.css from atomic-age/tokens.json.
// Atomic Age's bundle.css expects a tokens.css loaded before it, but the
// design system doesn't ship one — this is that missing piece. Re-run
// whenever ../../atomic-age/tokens.json changes.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(
  readFileSync(path.join(__dirname, "../../atomic-age/tokens.json"), "utf8")
);

function themeVars(theme) {
  return tokens.color.tokens
    .map((t) => {
      const value = typeof t.value === "string" ? t.value : t.value[theme];
      return `  --${t.name}: ${value};`;
    })
    .join("\n");
}

const staticVars = [
  `  --font-display: ${tokens.type.families.display};`,
  `  --font-sans: ${tokens.type.families.sans};`,
  `  --font-body: ${tokens.type.families.body};`,
  ...tokens.spacing.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ...tokens.radius.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ...tokens.opacity.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ...tokens.zIndex.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ...tokens.breakpoint.tokens.map((t) => `  --${t.name}: ${t.value};`),
].join("\n");

const shadowVars = (theme) =>
  tokens.shadow.tokens.map((t) => `  --${t.name}: ${t.value[theme]};`).join("\n");

const css = `/* Generated by scripts/build-tokens.mjs from atomic-age/tokens.json. Do not hand-edit. */

:root {
${staticVars}
${themeVars("light")}
${shadowVars("light")}
}

@media (prefers-color-scheme: dark) {
  :root {
${themeVars("dark")}
${shadowVars("dark")}
  }
}
`;

writeFileSync(path.join(__dirname, "../assets/atomic-age/tokens.css"), css);
console.log("Wrote assets/atomic-age/tokens.css");
